channel_code = {
'Первый канал': '1_kanal', 
'Россия': 'rossiya',
'НТВ': 'ntv',
'СТС': 'sts',
'РЕН ТВ': 'ren-tv',
'ТНТ': 'tnt',
'Пятый канал': '5_tv',
'ТВ Центр': 'tvts',
'ОТР': 'otr',
'Домашний': 'domashnijo',
'Моя планета': 'moya_planeta',
'Перец': 'prz',
'РБК': 'rbk',
'Россия 24': 'vesti',
'Euronews': 'euronews',
'Музыка Первого': 'myzyka_pervogo',
'A one': 'a-one',
'Europa Plus TV': 'europa_plus_tv',
'Пятница!': 'friday',
'Mezzo': 'mezzo',
'Россия 2': 'sport',
'НТВ+ Наш футбол': 'ntv-plyus-nash_fytbol',
'Спорт 1 (Россия)': 'sport_1',
'Eurosport': 'eurosport',
'Eurosport 2': 'eurosport_2',
'Viasat Sport': 'viasat_sport',
'Extreme Sports Channel': 'extreme_sports',
'Русский Экстрим': 'rysskijo_ekstrim',
'Дом кино': 'dom_kino',
'Русский иллюзион': 'rysskijo_illyuzion',
'ТВ3': 'tv3',
'НСТ (Страшное)': 'nastoyaschee_strashnoe_televidenie',
'TV1000': 'tv1000',
'TV1000 Русское кино': 'tb1000_rysskoe_kino',
'TV1000 Action': 'tv1000__action',
'Феникс+Кино': 'feniks_art',
'E!: Entertainment Television': 'diva',
'SET': 'set',
'Sony Sci-Fi': 'sony_sci-fi',
'Universal Channel': 'universal',
'Fox Life': 'fox_life',
'FOX': 'fox',
'Nat Geo Wild': 'nat_geo_wild',
'Viasat Nature': 'viasat_nature',
'Viasat Explorer': 'viasat_explorer',
'Viasat History': 'viasat_history',
'Travel Channel': 'travel_channel',
'National Geographic Channel': 'national_geographic',
'24 Техно': '24_tehno',
'Охота и рыбалка': 'ohota_i_rybalka',
'Культура': 'kyltyra',
'Звезда': 'zhvezda',
'Ля-Минор': 'lya-minor_tv',
'Время': 'vremya__dalekoe_i_blizkoe',
'Ностальгия': 'nostalgiya',
'Дождь': 'dozhd',
'Комедия ТВ': 'komediya_tv',
'TV XXI': 'tv_xxi',
'TНТ-Comedy': 'komedi_tv',
'Ретро': 'retro_tv', 
'КХЛ ТВ': 'khl',
'BabyTV': 'baby_tv',
'Disney Channel': 'disney_channel',
'Cartoon Network': 'cartoon_network',
'Nickelodeon': 'nickelodeon',
'Мультимания': 'myltimaniya',
'Карусель': 'karysel',
'Детский Мир': 'detski_mir',
'Наука 2.0': 'nauka_2_0',
'Детский': 'detskijo',
'Boomerang': 'boomerang',
'JimJam': 'jimjam',
'TiJi': 'tiji',
'Gulli': 'gulli',
'Драйв': 'drive', 
'Авто плюс': 'avtoplyus_tv',
'Телекафе': 'telekafe',
'Шансон ТВ': 'shanson_tv',
'Вопросы и ответы': 'voprosy_i_otvety',
'CNN International': 'cnn',
'BBC World News': 'bbc_world',
'Усадьба': 'usadba',
'Спорт': 'sport_',
'Бойцовский клуб': 'boicovskii_klub',
'World Fashion Channel': 'world_fashion_channel',
'НТВ+ Баскетбол': 'ntv-pljus_basketbol',
'НТВ+ Спорт': 'ntv-pljus-sport',
'НТВ+ Футбол': 'ntv-pljus-fytbol',
'Много ТВ': 'mnogo_tv',
'Индия ТВ': 'indiya_tv',
'RU.TV': 'ru.tv',
'365 Дней ТВ': '365_dnejo_tv',
'2х2': '2х2',
'Ю': 'u-tv',
'ЖИВИ!': 'givi',
'Беларусь 24': 'belarys-tv',
'Киноклуб': 'kinoklyb',
'Кино плюс': 'kino_pljus', 
'Еврокино': 'evrokino',
'Спас': 'spas', 
'CBS Drama': 'cbs_drama',
'CBS Reality': 'cbs_reality'
}
