channel_code = {
'РТР-Планета': 'rtr_planet',
'TVCI': 'tvci',
'Eurosport': 'eurosport',
'Дом кино': 'dom_kino',
'Наше кино': 'nashe_kino',
'TV1000 Русское кино': 'tv1000_rus_kino',
'Diva Universal': 'hallmark',
'Animal Planet': 'animal_planet',
'Viasat History': 'viasat_history',
'National Geographic Channel': 'nationalgeographic',
'Время': 'vremya',
'TV XXI': 'kanal_xxi',
'RTVi': 'rtv_international',
'Беларусь 24': 'belarus_24',
'Первый Балтийский': '1balt',
'TV8': 'tv8',
'TV3 Lietuva': 'tv3',
'TV6 Lietuva': 'tv6',
'LNK': 'lnk',
'LRT': 'lrt',
'LRT Kultura': 'lrt-culture',
'BTV': 'btv',
'Lietuvos Rytas TV': 'tv5',
'TV1': 'tv1',
'Viasat Sport Baltic LT': 'viasat_sport_baltic', 
'Sport1': 'sport1'
}
